[package]
name = "battlesnake-doctor-strangle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0"
pretty_env_logger = "0"
tokio = { version = "1", features = ["full"] }
warp = "0"
serde = { version = "1.0.140", features = ["derive"] }
itertools = "0.10.3"
